AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - bin/*
  - db/**/*
  - node_modules/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StderrPuts:
  Enabled: false
